import * as THREE from 'three';
const rooms={living:{k:'ROOM 01',t:'Living Room',m:'25.0°C · 3 active',d:[['LIGHT 01','FADO Lamp','68%'],['MEDIA 01','Television','Apple TV'],['MEDIA 02','Apple TV','Playing'],['CLIMATE 01','Air Conditioning','23.5°'],['CLEAN 01','Robot Vacuum','Docked']]},bedroom:{k:'ROOM 02',t:'Bedroom',m:'22.5°C · 2 active',d:[['LIGHT 01','Bedside Lamp','35%'],['LIGHT 02','Ceiling Light','Off'],['CLIMATE 01','Air Conditioning','22.5°'],['SWITCH 01','Bedside Switch','On']]},kitchen:{k:'ROOM 03',t:'Kitchen',m:'24.0°C · 2 active',d:[['LIGHT 01','Pendant Lights','82%'],['LIGHT 02','Counter Light','On'],['SWITCH 01','Main Switch','On'],['CLIMATE 01','Air Conditioning','24.0°'],['CLEAN 01','Robot Vacuum','Kitchen']]}};
let s={page:'home',room:'living',di:0,power:true,hue:.105,light:.68,exploded:false};
const canvas=document.querySelector('#scene'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(30,1,.1,100);camera.position.set(0,0,8);const root=new THREE.Group();scene.add(root);scene.add(new THREE.HemisphereLight(0xffffff,0x111111,1.8));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(3,4,5);scene.add(key);const rim=new THREE.PointLight(0xffffff,8,10);rim.position.set(-3,1,3);scene.add(rim);
function clear(){while(root.children.length){const o=root.children.pop();o.traverse(x=>{x.geometry?.dispose();if(x.material)(Array.isArray(x.material)?x.material:[x.material]).forEach(m=>m.dispose())})}}
function mat(c,r=.28,m=.35){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function roomObj(){clear();const g=new THREE.Group();const body=new THREE.Mesh(new THREE.SphereGeometry(1.18,96,64),new THREE.MeshPhysicalMaterial({color:0x1b1a19,roughness:.18,metalness:.2,clearcoat:1,clearcoatRoughness:.12}));g.add(body);for(let i=0;i<3;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(1.55+i*.3,.008,8,200),new THREE.MeshBasicMaterial({color:0x817b74,transparent:true,opacity:.2-i*.03}));r.rotation.set(Math.PI/2+i*.12,i*.25,i*.5);g.add(r)}root.add(g)}
function lampObj(){clear();const g=new THREE.Group(),c=new THREE.Color().setHSL(s.hue,.72,.58);const base=new THREE.Mesh(new THREE.CylinderGeometry(.72,.82,.58,80),mat(0x171717,.18,.65));base.position.y=-.62;g.add(base);const shade=new THREE.Mesh(new THREE.SphereGeometry(1.05,96,64,0,Math.PI*2,0,Math.PI*.74),new THREE.MeshPhysicalMaterial({color:c,emissive:c,emissiveIntensity:s.power?s.light*1.6:.01,roughness:.32,transmission:.1,transparent:true,opacity:.98}));shade.position.y=.28;shade.scale.y=.9;g.add(shade);const glow=new THREE.PointLight(c,s.power?10*s.light:0,8);glow.position.set(0,.4,1.2);g.add(glow);if(s.exploded){shade.position.y=1.05;base.position.y=-1.2;const ring=new THREE.Mesh(new THREE.TorusGeometry(.7,.025,12,100),mat(0x6f6b66,.2,.5));ring.position.y=-.28;ring.rotation.x=Math.PI/2;g.add(ring)}root.add(g)}
function tvObj(){clear();const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.BoxGeometry(3,1.72,.13),mat(0x070707,.12,.6)));const screen=new THREE.Mesh(new THREE.PlaneGeometry(2.72,1.44),new THREE.MeshBasicMaterial({color:0x303238}));screen.position.z=.07;g.add(screen);root.add(g)}
function boxObj(){clear();const b=new THREE.Mesh(new THREE.BoxGeometry(2.2,2.2,.48),mat(0x111111,.14,.65));b.rotation.set(-.35,.42,.22);root.add(b)}
function climateObj(){clear();const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.TorusGeometry(1.45,.11,28,180),mat(0xdad4cb,.2,.3)));g.add(new THREE.Mesh(new THREE.CircleGeometry(1.27,100),new THREE.MeshBasicMaterial({color:0x151515})));root.add(g)}
function vacuumObj(){clear();const g=new THREE.Group();const b=new THREE.Mesh(new THREE.CylinderGeometry(1.3,1.34,.4,90),mat(0x151515,.18,.65));b.rotation.x=Math.PI/2;g.add(b);root.add(g)}
function colourSphere(){clear();const geo=new THREE.SphereGeometry(1.55,128,96),colors=[];for(let i=0;i<geo.attributes.position.count;i++){const x=geo.attributes.position.getX(i),y=geo.attributes.position.getY(i),z=geo.attributes.position.getZ(i);const hue=(Math.atan2(z,x)/(Math.PI*2)+1)%1,sat=.78,lit=.56+(y/1.55)*.14;const c=new THREE.Color().setHSL(hue,sat,THREE.MathUtils.clamp(lit,.34,.76));colors.push(c.r,c.g,c.b)}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const sphere=new THREE.Mesh(geo,new THREE.MeshPhysicalMaterial({vertexColors:true,roughness:.24,metalness:.04,clearcoat:1,clearcoatRoughness:.15}));sphere.name='hueSphere';root.add(sphere);const halo=new THREE.Mesh(new THREE.TorusGeometry(2.05,.008,8,220),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.13}));halo.rotation.x=Math.PI/2;root.add(halo);root.scale.setScalar(.8+s.light*.42)}
function build(){if(s.page==='colour')colourSphere();else if(s.page==='home'||s.page==='room')roomObj();else{const d=rooms[s.room].d[s.di];if(d[0].includes('LIGHT')||d[0].includes('SWITCH'))lampObj();else if(d[1]==='Television')tvObj();else if(d[1]==='Apple TV')boxObj();else if(d[0].includes('CLIMATE'))climateObj();else vacuumObj()}}
function show(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===p));s.page=p;build();wipe()}
function wipe(){const w=document.querySelector('#wipe');w.classList.remove('go');void w.offsetWidth;w.classList.add('go')}
function enterRoom(k){s.room=k;const r=rooms[k];roomKicker.textContent=r.k;roomTitle.textContent=r.t;roomMeta.textContent=r.m;roomCount.textContent=`0${Object.keys(rooms).indexOf(k)+1} / 03`;objectList.innerHTML='';r.d.forEach((d,i)=>{const b=document.createElement('button');b.innerHTML=`<span>${d[0]}</span><b>${d[1]}</b><em>${d[2]}</em>`;b.onclick=()=>openDevice(i);objectList.appendChild(b)});show('room');menu.classList.remove('open')}
function openDevice(i){s.di=i;s.exploded=false;const d=rooms[s.room].d[i];deviceKicker.textContent=d[0];deviceTitle.textContent=d[1];deviceMeta.textContent=d[0].includes('LIGHT')?'Rotate the object. Open colour to tune it.':'Rotate the object to inspect and control it.';deviceIndex.textContent=`0${i+1} / 0${rooms[s.room].d.length}`;colourBtn.style.display=d[0].includes('LIGHT')||d[0].includes('SWITCH')?'block':'none';show('device')}
document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>enterRoom(b.dataset.room));document.querySelectorAll('[data-go="home"]').forEach(b=>b.onclick=()=>{show('home');menu.classList.remove('open')});menuBtn.onclick=()=>menu.classList.add('open');closeMenu.onclick=()=>menu.classList.remove('open');backRoom.onclick=()=>show('room');backDevice.onclick=()=>show('device');explodeBtn.onclick=()=>{s.exploded=!s.exploded;explodeBtn.classList.toggle('active',s.exploded);build()};colourBtn.onclick=()=>show('colour');powerBtn.onclick=()=>{s.power=!s.power;powerBtn.textContent=s.power?'ON':'OFF';powerBtn.classList.toggle('active',s.power);build()};
const keys=Object.keys(rooms);prevRoom.onclick=()=>enterRoom(keys[(keys.indexOf(s.room)+2)%3]);nextRoom.onclick=()=>enterRoom(keys[(keys.indexOf(s.room)+1)%3]);prevDevice.onclick=()=>openDevice((s.di-1+rooms[s.room].d.length)%rooms[s.room].d.length);nextDevice.onclick=()=>openDevice((s.di+1)%rooms[s.room].d.length);
let drag=false,px=0,py=0,touches=new Map(),pinch=0;function applyHue(dx,dy){s.hue=(s.hue+dx*.0018)%1;if(s.hue<0)s.hue+=1;hueReadout.textContent=Math.round(s.hue*360)+'°';root.rotation.y+=dx*.006;root.rotation.x+=dy*.004}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);touches.set(e.pointerId,{x:e.clientX,y:e.clientY});drag=true;px=e.clientX;py=e.clientY;if(touches.size===2){const a=[...touches.values()];pinch=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}});canvas.addEventListener('pointermove',e=>{if(!touches.has(e.pointerId))return;touches.set(e.pointerId,{x:e.clientX,y:e.clientY});if(s.page==='colour'&&touches.size===2){const a=[...touches.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),delta=d-pinch;pinch=d;s.light=THREE.MathUtils.clamp(s.light+delta*.0025,.05,1);brightnessReadout.textContent=Math.round(s.light*100)+'%';root.scale.setScalar(.8+s.light*.42)}else{const dx=e.clientX-px,dy=e.clientY-py;px=e.clientX;py=e.clientY;if(s.page==='colour')applyHue(dx,dy);else{root.rotation.y+=dx*.006;root.rotation.x+=dy*.004}}});function end(e){touches.delete(e.pointerId);drag=touches.size>0}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();build();const animClock=new THREE.Clock();function loop(){requestAnimationFrame(loop);const t=animClock.getElapsedTime();if(!drag){root.rotation.y+=.0015;root.position.y=Math.sin(t*.7)*.04}renderer.render(scene,camera)}loop();setInterval(()=>document.querySelector('#clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),1000);